resources:
# Comment the following 1 lines if you want to disable
# the auth proxy (https://github.com/brancz/kube-rbac-proxy)
# which protects your /metrics endpoint.
- auth_proxy_service.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml